model_help = "Model is set to Llama-3.3-70B Instruct model, an all-rounded model capbable of handling long context data"

rubrics_help = ":Upload a set of marking rubrics with a **criterion** column in PDF."

report_help ="Report with more than 3,000 words may experience '*max limit token error*'. Click on **Clear History** and try again."

eval_btn_help = "Click to evaluate the internship report"

zip_help = "Upload a zip file by project group."

intro_var = """
While AI marking can help with consistency and efficiency, it's crucial to review and verify the marks and feedback generated.
"""

disclaimer_var = "Disclaimer: This AI-powered tool is designed to assist in marking reports by providing helpful suggestions and evaluations. However, it may occasionally make errors or misinterpret content. Final judgment and accuracy should be verified by a qualified evaluator."

creator_var = "Andy Oh is the creator behind this AI-powered tool, designed to transform how educators manage their workload by introducing an innovative solution to streamline their tasks." 

summary_report_var = "Use it as a reference source when evaluating the summary report generated by students."

main_py_error = ":red[*Error running 'main.py'. It could be missing python files or code errors like IndexError during the program execution using our test data*]."

app_usage_text = """

Respect the App Usage

This app is free to use, but permission is required before access. 
Upon approval, you will receive a User ID and Password. 
To request access, email: andy_oh18@yahoo.com.\n

"""


development_msg = "Please note that this app is still under active development."

togetherai_signup_msg = "Sign up an account to generate an API key that comes with a $1 free credit"